# Экшен для выпуска бета-версий ресурспака на Modrinth и CurseForge

name: Выпустить бету на сайты

on:
  workflow_dispatch:

jobs:
  build_and_release:
    name: Сборка и выпуск
    runs-on: ubuntu-latest